### ISSUE TITLE
Fix JWT deeplink login button

### ISSUE THREAD

**Issue by shapkarin** [aeternity/jitsi-meet#63] opened 2020-07-02 13:02 UTC
It must be appears to all users, not only for moderators.

**Comment by shapkarin** [comment] 2020-07-02 13:04
also it is not always accessible because of popup

**Comment by venimus** [comment] 2020-07-02 13:06
![image](https://user-images.githubusercontent.com/632282/86362322-c9c0a180-bc7d-11ea-8160-d1335aa17e64.png)

I think better have this button appear also in this popup (deeplink/webwallet) because i'm the host button is opening a login form which does not work anymore (we cant have jwt and password login work together)

**Comment by mradkov** [comment] 2020-07-02 13:07
Can you add it to the menu here
<img width="596" alt="Screenshot 2020-07-02 at 16 07 00" src="https://user-images.githubusercontent.com/13139371/86362522-1310f100-bc7e-11ea-83d2-17337943dd5c.png">

**Comment by mradkov** [comment] 2020-07-02 13:07
I think this is a duplicate of https://github.com/aeternity/jitsi-meet/issues/44

**Closed as completed** 2020-07-03 09:26 UTC
Labels: bug, area/ui
